use hcl2;
create table electricity_connection_type( id int primary key, connection_name varchar(20) not null);
desc electricity_connection_type;
create table slab(id int primary key, connection_id int not null,from_unit int not null,to_unit int not null,rate double not null,constraint connection_id_FK foreign key(connection_id)references electricity_connection_type(id));
desc slab;
create table building_type(id int primary key,name varchar(100) not null,connection_type1_id int(20) not null,constraint connection_type1_id_FK foreign key(connection_type1_id)references electricity_connection_type(id));
desc building_type;
show tables;
create table buildings(id int primary key,owner_name varchar(100) not null,address varchar(100) not null,building_id  int not null,email_address varchar(100) not null,constraint building_id_FK foreign key(building_id) references buildings(id));
desc bulidings;
alter table buildings change owner_name building_owner_name varchar(100);
desc buildings;
alter table buildings modify address varchar(255);
desc buildings;
alter table electricity_connection_type add constraint check_connection_name check(connection_name in('home','commercial'));
desc electricity_connection_type;
alter table buildings rename to building_details;
drop table slab;
drop table building_details;
insert into electricity_connection_type values(1,'pondy');
insert into electricity_connection_type values(2,'chennai');
create table slab (id int primary key,connection_id int not null,from_unit int not null,to_unit int not null,rate double not null,constraint connection_id_FK foreign key(connection_id)references electricity_connection_type(id));
insert into slab(id,connection_id,from_unit,to_unit,rate)values(1,1,1,10.0,5.0);
insert into slab(id,connection_id,ffrom_unit,to_unit,rate)values(2,2,2,100.15,5.0);
insert into electricity_connection_type(id,connection_name)values(3,'thirchy'),(4,'madurai'),(5,'salem');
insert into building_type(id,name,connection_type1_id)values(1,'home',1),(2,'app',2),(3,'land',3),(4,'godown',4),(5,'school',5);
update slap set from_unit=1 where connection_type_id in (1,2);
insert into building_type(id,name,connection_type1_id)values(6,'shpping mall',1);
update building_type set name1='mall' where name1='shopping mall';

